"use client";

// import type { Metadata } from "next";

import "./globals.css";
import { cn } from "@/lib/utils";
import { Provider } from "react-redux";
import { store } from "@/redux/store";

// export const metadata: Metadata = {
//   title: "Synapsis - Blog",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("min-h-screen bg-background antialiased font-roboto")}
      >
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
